from django.db import models
from django.conf import settings
from core.models import TimeStampedModel

class RepositoryAnalysis(TimeStampedModel):
    """
    Stores analysis metadata for a GitHub repository.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='repositories')
    repo_url = models.URLField(max_length=500, db_index=True)
    repo_name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_private = models.BooleanField(default=False)
    last_analyzed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.repo_name} ({self.user.email})"

class Review(TimeStampedModel):
    """
    Represents a single code review request (e.g., for a PR, file, or snippet).
    """
    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        PROCESSING = 'PROCESSING', 'Processing'
        COMPLETED = 'COMPLETED', 'Completed'
        FAILED = 'FAILED', 'Failed'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='reviews')
    repository = models.ForeignKey(RepositoryAnalysis, on_delete=models.SET_NULL, null=True, blank=True, related_name='reviews')
    
    title = models.CharField(max_length=255)
    code_snippet = models.TextField(blank=True, null=True) # Used if it's a snippet review
    pull_request_url = models.URLField(max_length=500, blank=True, null=True) # Used if PR review
    language = models.CharField(max_length=50, db_index=True)
    
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING, db_index=True)
    overall_score = models.FloatField(null=True, blank=True) # e.g. 85.5 code health
    summary = models.TextField(blank=True, null=True)
    error_message = models.TextField(blank=True, null=True) # Used if AI processing fails
    
    is_saved = models.BooleanField(default=False, db_index=True) # For bookmarking review history

    def __str__(self):
        return f"Review {self.id} - {self.status}"

class ReviewFeedback(TimeStampedModel):
    """
    Stores the granular feedback items generated by the AI for a specific review.
    """
    class Severity(models.TextChoices):
        LOW = 'LOW', 'Low'
        MEDIUM = 'MEDIUM', 'Medium'
        HIGH = 'HIGH', 'High'
        CRITICAL = 'CRITICAL', 'Critical'

    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='feedbacks')
    file_path = models.CharField(max_length=500)
    line_number = models.IntegerField(null=True, blank=True)
    issue_type = models.CharField(max_length=100) # e.g. "Security", "Performance", "Clean Code"
    severity = models.CharField(max_length=20, choices=Severity.choices, default=Severity.MEDIUM, db_index=True)
    
    description = models.TextField()
    suggestion = models.TextField() # The proposed fix/code

    def __str__(self):
        return f"Feedback {self.id} for Review {self.review.id}"
