# Generated by Django 6.0.5 on 2026-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
